
# html lang
language: cn

# main menu navigation
menu:
  Home: /
  About: /about
  Favorites: /favorites
  # Contact: /contact
  Archives: /archives
  # Categories: /categories

header-img: /img/home-bg.png

sidebar-avatar: /images/avatar.png
sidebar-about-description: 絶滅危惧種を食べよう！

# Set rss to false to disable feed link.
# Leave rss as blank to use site's feed link, and install hexo-generator-feed: `npm install hexo-generator-feed --save`.
# Set rss to specific value if you have burned your feed already.
RSS: true

social:
  GitHub: https://github.com/tobelight || github
  E-Mail: mailto://tobelight@outlook.com || envelope
  # Weibo: https://weibo.com/yourname || weibo
  # Google: https://plus.google.com/yourname || google
  # Twitter: https://twitter.com/yourname || twitter
  # FB Page: https://www.facebook.com/yourname || facebook
  # VK Group: https://vk.com/yourname || vk
  # StackOverflow: https://stackoverflow.com/yourname || stack-overflow
  # YouTube: https://youtube.com/yourname || youtube
  # Instagram: https://instagram.com/yourname || instagram
  # Skype: skype:yourname?call|chat || skype
  # Juejin: juejinlink || || 掘

# Featured Tags
featured-tags: true                     # whether or not using Feature-Tags
featured-condition-size: 1              # A tag will be featured if the size of it is more than this condition value

# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: false

# 友链
friends_title: FRIENDS
friends:
  # 22Infinite: https://www.22infinite.com/
  # Jsonz: https://jsonz1993.github.io/
  # XuYuwas: https://xuyuwas.github.io/


# MathJax rendering for layout:page (e.g. post preview)
page-mathjax: false

# giscus
# https://github.com/giscus/giscus
giscus:
  enable: true
  repo: tobelight/tobelight.github.io
  repo_id: R_kgDOL9QVNg

# Code Highlight theme
# Available value:
#    normal | night | night yilia | night eighties | night blue | night bright
# https://github.com/chriskempson/tomorrow-theme
# night yilia - https://github.com/litten/hexo-theme-yilia
highlight_theme: normal

# Show Views / Visitors of the website / page with busuanzi.
# Get more information on http://ibruce.info/2015/04/04/busuanzi
# todo
busuanzi_count:
  enable: true
  total_visitors: true
  total_views: true
  post_views: true

# Baidu Analytics ID
baidu_analytics:
  tracking_id: 
  localhost_ignored: true

# Google Analytics
google_analytics:
 tracking_id: G-N1MYYTXMZR
 localhost_ignored: true

# Creative Commons 4.0 International License.
# See: https://creativecommons.org/share-your-work/licensing-types-examples
# Available values of license: by | by-nc | by-nc-nd | by-nc-sa | by-nd | by-sa | zero
# You can set a language value if you prefer a translated version of CC license.
# CC licenses are available in 39 languages, where you can find the specific and correct abbreviation you need.
# Valid values of language: deed.zh, deed.fr, deed.de, etc.
creative_commons:
  license: by-nc-sa
  sidebar: false
  post: true
  language: deed.zh

# Reward (Donate)
reward_settings:
  # If true, reward would be displayed in every article by default.
  # You can show or hide reward in a specific article throuth `reward: true | false` in Front Matter.
  enable: true
  comment: 如果这篇文章对你有帮助，那么不妨？

reward:
  wechatpay: /img/fadian-x.jpg
  alipay: /img/fadian-x.jpg

# Search
# To enable the search function, you need to install the hexo-generator-search, and set `search.path: search.json` in root config.
# run `npm install hexo-generator-search-hux` in blog root dit.
# https://github.com/tobelight/hexo-generator-search-hux
search:
  enable: true